server:
  port: 8080

# MongoDB Config
spring:
  application:
    name: lms-service
    version: 1.0
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/lms}

# External APIs
kyc:
  api:
    url: ${KYC_API_URL:https://kycapitest.credable.io/service/customerWsdl.wsdl}
scoring:
  score-threshold: 50
  api:
    url: ${SCORING_API_URL:https://scoringtest.credable.io/api/v1}

# Retry Configuration
  resilience4j:
    retry:
      instances:
        scoringService:
          maxAttempts: 5
          waitDuration: 5s
          enableExponentialBackoff: true



# Logging Configuration
logging:
  level:
    root: WARN
    com.credable.middleware: DEBUG
    org.springframework.data.mongodb: INFO

# OpenAPI/Swagger Configuration
springdoc:
  api-docs:
    path: /v1/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    disable-swagger-default-url: true
  show-actuator: true
  server:
    url: http://localhost:8080
  packages-to-scan: com.credable.app.lms_service.controller

# Additional OpenAPI Information
openapi:
  info:
    title: ${spring.application.name} API
    description: API Documentation for ${spring.application.name}
    version: ${spring.application.version}
    terms-of-service: https://credable.com/terms
    contact:
      name: Credable Development Team
      email: team@credable.com
      url: https://example.com/contact
    license:
      name: Apache 2.0
      url: https://www.apache.org/licenses/LICENSE-2.0

